Integrate git cloning and pushing
tomsquest/docker-radicale pull request #83
Opened 2020-09-21 05:58 UTC by DylanVanAssche

This PR adds the setup to use git cloning and pushing of your CalDAV/CardDAV files.

You need the following environment variables:

1. `GIT_REPOSITORY`: The repository URL, with username and password, example: `https://myuser:mypass@github.com/myuser/myrepo`
2. `GIT_USERNAME`: The username to be used for commits
3. `GIT_EMAIL`: The email to be used for commits

And enable the `hook` in your config file:

```
[storage]
hook = git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s) && git push origin master
```

This option is fully optional, if the environment variables are not defined, the git repository is not used.
Looking forward to your review :)

2020-09-21 12:47 UTC, tomsquest requested changes
Hi @DylanVanAssche ,

Thanks for your contribution.
All seems OK :+1: .
There is one typo.

Can you add a section to the Readme to help user configure it? 
(for adding the storage section you explained in this PR).

2020-09-21 12:47 UTC, tomsquest commented on docker-entrypoint.sh
> +    # Git needs to know an indentity for pushing changes
typo in `indentity`

2020-09-21 14:54 UTC, DylanVanAssche commented
Done :+1:

2020-09-23 06:41 UTC, tomsquest approved these changes

2020-09-23 06:45 UTC, merged

2020-09-23 09:47 UTC, tomsquest commented
@DylanVanAssche Your PR has been merged, I will publish a new version soon.
Thanks for your contribution.

2020-09-23 10:09 UTC, tomsquest commented
Released in  `2.1.12.2`